nccl4py/cute: Minimal reproduction of cute gin barrier alignment bug
This triggers cudaErrorMisalignedAddress error in NCCL 2.30.7 +
nccl4py 0.3.1 with the following message:

Traceback (most recent call last):
  File "/opt/tiger/nccl-src/bindings/nccl4py/examples/cute/main2.py", line 222, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/tiger/nccl-src/bindings/nccl4py/examples/cute/main2.py", line 202, in main
    device.sync()
  File "cuda/core/_device.pyx", line 1434, in cuda.core._device.Device.sync
  File "cuda/core/_utils/cuda_utils.pyx", line 211, in cuda.core._utils.cuda_utils.handle_return
  File "cuda/core/_utils/cuda_utils.pyx", line 203, in cuda.core._utils.cuda_utils._check_error
  File "cuda/core/_utils/cuda_utils.pyx", line 179, in cuda.core._utils.cuda_utils._check_runtime_error
cuda.core._utils.cuda_utils.CUDAError: cudaErrorMisalignedAddress: The device encountered a load or store instruction on a memory address which is not aligned. This leaves the process in an inconsistent state and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched.